version: 0.1
frontend:
  phases:
    build:
      commands:
        - yarn install
  artifacts:
    baseDirectory: storybook-static
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
